export const CONFIG = {
  CHILD_PROCESS_MAX_BUFFER: Number(process.env.GCM_MAX_BUFFER) || 50 * 1024 * 1024,
  MAX_HUNKS: Number(process.env.GCM_MAX_HUNKS || 16),
  FILE_CONCURRENCY: Number(process.env.GCM_FILE_CONCURRENCY || 4),
  PER_FILE_BUFFER: Number(process.env.GCM_PER_FILE_BUFFER || 1 * 1024 * 1024),
  MODEL_NAME: process.env.GCM_MODEL || process.env.GEMINI_MODEL || 'gemini-2.5-flash',
  TEMPERATURE: Number(process.env.GCM_TEMPERATURE || process.env.GEMINI_TEMP || 1),
  ENABLE_THINKING: (process.env.GCM_ENABLE_THINKING || 'false') === 'true',
  TOKEN_BYTES_RATIO: Number(process.env.GCM_TOKEN_BYTES_RATIO || 3.5),
  MAX_CONTEXT_TOKENS: Number(process.env.GCM_MAX_CONTEXT_TOKENS || 1048576),
  MAX_OUTPUT_TOKENS: Number(process.env.GCM_MAX_OUTPUT_TOKENS || 2048),
  MAX_INPUT_TOKENS: Number(process.env.GCM_MAX_INPUT_TOKENS || 100000),
  MAX_INPUT_TOKENS_SAFETY_FACTOR: Number(process.env.GCM_MAX_INPUT_TOKENS_SAFETY_FACTOR || 0.5),
  ENABLE_HUNK_WEIGHTS: (process.env.GCM_ENABLE_HUNK_WEIGHTS || 'false') === 'true',
  LOG_LEVEL: process.env.GCM_LOG_LEVEL || 'info',
  TELEMETRY_FILE: process.env.GCM_TELEMETRY_FILE || '',
  GEMINI_MAX_RETRIES: Number(process.env.GCM_GEMINI_MAX_RETRIES || 3),
  GEMINI_RETRY_BASE_MS: Number(process.env.GCM_GEMINI_RETRY_BASE_MS || 1000),
  GEMINI_RETRY_MAX_MS: Number(process.env.GCM_GEMINI_RETRY_MAX_MS || 60000),
};
